// Workers-safe AI helpers for the news pipeline.
//
// IMPORTANT — billing mode. News is a BACKGROUND-AI app: summaries, podcast
// scripts and article images are generated by cron/queue jobs with no end
// user present. The published app runs in ugly.bot auth mode ("Mode A"),
// where the framework's AiText/AiImage clients force the *user-billed*
// endpoint (`/user-billed/text`) and require an end-user session token — which
// background jobs don't have (→ UnauthenticatedAiCallError). So we call the
// *owner-billed* proxy endpoints directly with the app's owner AI token
// (`AI_PROXY_TOKEN`, minted at publish), exactly the shape AiText/AiImage use
// in owner mode. Pure `fetch` — bundles for Node and Workers.
import type { ImageGenModel } from 'ugly-app/shared';

export type ChatMessage = { role: 'system' | 'user' | 'assistant'; content: string };

const DEFAULT_AI_PROXY_URL = 'https://api.ugly.bot/v1/ai';

function aiProxy(): { baseUrl: string; token: string } {
  /* eslint-disable @typescript-eslint/dot-notation */
  const baseUrl = (process.env['AI_PROXY_URL'] ?? DEFAULT_AI_PROXY_URL).replace(/\/$/, '');
  const token = process.env['AI_PROXY_TOKEN'] ?? '';
  /* eslint-enable @typescript-eslint/dot-notation */
  return { baseUrl, token };
}

type ContentPart = { type: string; text?: string; thinking?: string };
/** The proxy returns `message.content` as a string OR an array of parts
 *  (gpt → string; reasoning models → [{type:'thinking'}, {type:'text'}]). */
function extractContent(data: unknown): string {
  const msg = (data as { message?: { content?: unknown }; content?: unknown }).message;
  const content = msg?.content ?? (data as { content?: unknown }).content;
  if (typeof content === 'string') return content.trim();
  if (Array.isArray(content)) {
    const text = (content as ContentPart[])
      .filter((p) => p.type === 'text' && typeof p.text === 'string')
      .map((p) => p.text)
      .join('')
      .trim();
    return text;
  }
  return '';
}

/** Owner-billed text generation via the ugly.bot AI proxy. */
export async function genText(
  messages: ChatMessage[],
  opts: { model: string; temperature?: number; maxTokens?: number },
): Promise<string | null> {
  const { baseUrl, token } = aiProxy();
  if (!token) { console.warn('[news/ai] genText: AI_PROXY_TOKEN not set'); return null; }
  try {
    const res = await fetch(`${baseUrl}/text`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: opts.model,
        messages,
        userId: 'uglyBot',
        options: {
          ...(opts.temperature !== undefined ? { temperature: opts.temperature } : {}),
          ...(opts.maxTokens !== undefined ? { maxTokens: opts.maxTokens } : {}),
        },
      }),
    });
    if (!res.ok) {
      console.warn(`[news/ai] genText ${res.status}: ${(await res.text().catch(() => '')).slice(0, 200)}`);
      return null;
    }
    return extractContent(await res.json()) || null;
  } catch (error) {
    console.warn('[news/ai] genText failed', error);
    return null;
  }
}

/** Owner-billed image generation (returns a URL or data URI), or null. */
export async function genImage(
  prompt: string,
  opts?: { model?: ImageGenModel; negative?: string },
): Promise<string | null> {
  const { baseUrl, token } = aiProxy();
  if (!token) { console.warn('[news/ai] genImage: AI_PROXY_TOKEN not set'); return null; }
  const fullPrompt = opts?.negative ? `${prompt}\n\nAvoid: ${opts.negative}` : prompt;
  try {
    const res = await fetch(`${baseUrl}/image`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: opts?.model ?? 'flux_1_dev',
        prompt: fullPrompt,
        userId: 'uglyBot',
        options: { aspectRatio: 'landscape_16_9' },
      }),
    });
    if (!res.ok) {
      console.warn(`[news/ai] genImage ${res.status}: ${(await res.text().catch(() => '')).slice(0, 200)}`);
      return null;
    }
    const data = (await res.json()) as { url?: string; base64?: string; mime?: string };
    if (data.url) return data.url;
    if (data.base64) return `data:${data.mime ?? 'image/png'};base64,${data.base64}`;
    return null;
  } catch (error) {
    console.warn('[news/ai] genImage failed', error);
    return null;
  }
}

// Semantic embeddings (512-dim, matching the `file` collection's declared
// vector { dimensions: 512 } column) route through ugly.bot's `embedGen` proxy
// — NOT a direct OpenAI call. embedGen runs OpenAI text-embedding-3-small with
// the key held centrally in ugly.bot, and meters/bills the call against the
// app's account (same platform pattern as bahai-app). `createEmbeddingClient`
// from the workers adapter is a thin fetch wrapper over `uglyBotRequest`.
import { createEmbeddingClient } from 'ugly-app/server/adapter/workers';

const EMBED_DIMS = 512;
let embeddingClient: ReturnType<typeof createEmbeddingClient> | null = null;

/** ugly.bot embedGen embedding for feed ranking / search (512-dim), or null. */
export async function embed(text: string): Promise<number[] | null> {
  const input = text.trim().slice(0, 8000) || ' ';
  try {
    embeddingClient ??= createEmbeddingClient();
    const vec = await embeddingClient.embed(input, { dimensions: EMBED_DIMS });
    return vec ?? null;
  } catch (error) {
    console.warn('[news/ai] embed failed', error);
    return null;
  }
}

/** ~4 chars/token heuristic truncation (ported from ugly.bot Helper). */
export function truncateToApproximateTokens(text: string, maxTokens: number): string {
  const maxChars = maxTokens * 4;
  return text.length <= maxChars ? text : text.slice(0, maxChars);
}
