// Workers-safe AI helpers for the news pipeline.
//
// IMPORTANT — billing mode. News is a BACKGROUND-AI app: summaries, podcast
// scripts and article images are generated by cron/queue jobs with no end
// user present. The published app runs in ugly.bot auth mode ("Mode A"),
// where the framework's AiText/AiImage clients force the *user-billed*
// endpoint (`/user-billed/text`) and require an end-user session token — which
// background jobs don't have (→ UnauthenticatedAiCallError). So we call the
// *owner-billed* proxy endpoints directly with the app's owner AI token
// (`AI_PROXY_TOKEN`, minted at publish), exactly the shape AiText/AiImage use
// in owner mode. Pure `fetch` — bundles for Node and Workers.
import type { ImageGenModel } from 'ugly-app/shared';
import {
  createEmbeddingClient,
  getAdapter,
} from 'ugly-app/server/adapter/workers';
import { base64ToBytes } from '../../shared/news/WAV';
import type { NewsCategory } from '../../shared/news/types';

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

// NOTE: must match the live host. `api.ugly.bot` does NOT resolve — verified
// against the proxy; the working host is `ugly.bot/v1/ai` (same default
// server/news/email.ts uses). Prod normally sets AI_PROXY_URL at publish, but a
// correct fallback avoids a silent total-AI-outage if that env is ever missing.
const DEFAULT_AI_PROXY_URL = 'https://ugly.bot/v1/ai';

function aiProxy(): { baseUrl: string; token: string } {
  /* eslint-disable @typescript-eslint/dot-notation */
  const baseUrl = (process.env['AI_PROXY_URL'] ?? DEFAULT_AI_PROXY_URL).replace(
    /\/$/,
    '',
  );
  const token = process.env['AI_PROXY_TOKEN'] ?? '';
  /* eslint-enable @typescript-eslint/dot-notation */
  return { baseUrl, token };
}

// Bursty cron sweeps are the root cause of the `[cluster-*]` "genText returned
// null" / "both summaries non-substantive" errors: the hourly `newsHourly` tick
// fires feed downloads (→ per-article scrape genText+genImage) AND the cluster
// sweep (up to 8 synth × 2 genText + 8 satire × 1 genText, plus images) at the
// same instant. That flood of parallel proxy calls trips ugly.bot's rate
// limiter → HTTP 429 ("Rate limit exceeded"), and we used to give up on the
// first 429. Retry transient failures with exponential backoff + FULL jitter so
// the retries de-correlate and land after the limit window instead of hammering
// it again immediately. 4 attempts / ~≤7s worst case fits the 60s queue-job
// budget (even doubled by genSummary's substantive-retry loop).
const AI_MAX_ATTEMPTS = 4;

/** Transient statuses worth retrying (rate limit / timeout / server blip). A
 *  permanent 4xx (400/401/403) is NOT retried — it would just fail again. */
function isRetryableStatus(status: number): boolean {
  return status === 408 || status === 429 || status >= 500;
}

/**
 * Sleep for exponential backoff with full jitter. `attempt` is 1-based.
 *
 * 429 gets a much longer schedule than a 5xx blip because it is not a blip: the
 * proxy's limiter is a SLIDING 30-calls-per-60-SECONDS window per token
 * (PER_TOKEN_BURST.ai in ugly-bot/server/proxy/tokens.ts). Retrying a rate-limit
 * rejection ~7s later — the old ceiling for every status — lands inside the same
 * window and is rejected again, which is exactly how ~200 calls/hour burned all
 * four attempts and gave up. 2/4/8/16s (plus jitter, ~30s worst case) actually
 * outlives a meaningful slice of the window while staying inside the job budget.
 */
async function backoffDelay(attempt: number, status?: number): Promise<void> {
  const base =
    status === 429
      ? Math.min(2000 * 2 ** (attempt - 1), 16_000) // 2s, 4s, 8s, 16s
      : Math.min(500 * 2 ** (attempt - 1), 4000); // 500, 1000, 2000, 4000…
  const delay = base + Math.random() * base; // full jitter → [base, 2·base)
  await new Promise((resolve) => setTimeout(resolve, delay));
}

// ── Client-side pacing ──────────────────────────────────────────────────────
// Backoff alone only reacts to rejection; it never stops us from bursting into
// the limiter in the first place. The queue handler runs each batch's messages
// SEQUENTIALLY in one isolate (createWorkersApp's `for (const m of
// batch.messages)`), so an in-module gate genuinely paces a whole batch of up to
// 10 article scrapes — the tightest clustering we produce. Cloudflare still runs
// several batch invocations concurrently, so this is a smoothing measure, not a
// global bound; if 429s persist the exact fix is a `max_concurrency` on the
// queue consumer (the framework's ensureQueueConsumer currently sets only
// batch_size/max_retries/max_wait_time_ms, leaving Cloudflare's autoscaling
// default in place).
const MIN_CALL_GAP_MS = 2400; // ≈25 calls/min, headroom under the 30/60s cap
let lastCallStartedAt = 0;
let paceChain: Promise<unknown> = Promise.resolve();

/** Serialize proxy calls in this isolate, spacing each one MIN_CALL_GAP_MS. */
async function pace(): Promise<void> {
  const mine = paceChain.then(async () => {
    const since = Date.now() - lastCallStartedAt;
    if (since < MIN_CALL_GAP_MS) {
      await new Promise((r) => setTimeout(r, MIN_CALL_GAP_MS - since));
    }
    lastCallStartedAt = Date.now();
  });
  // Keep the chain alive even if a waiter is abandoned upstream.
  paceChain = mine.catch(() => undefined);
  await mine;
}

/**
 * POST JSON to an AI-proxy endpoint, retrying transient 429/5xx responses and
 * network errors with exponential backoff + jitter. Returns the final `Response`
 * (its body untouched, so the caller parses it) — which may still be `!ok` on a
 * permanent 4xx or after exhausting retries — or `null` if every attempt threw
 * before producing a response.
 */
async function postAi(
  baseUrl: string,
  path: string,
  token: string,
  body: unknown,
): Promise<Response | null> {
  let lastRes: Response | null = null;
  for (let attempt = 1; attempt <= AI_MAX_ATTEMPTS; attempt++) {
    try {
      await pace();
      const res = await fetch(`${baseUrl}${path}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });
      if (res.ok || !isRetryableStatus(res.status)) return res;
      lastRes = res;
      console.warn(
        `[news/ai] ${path} ${res.status} (attempt ${attempt}/${AI_MAX_ATTEMPTS})${attempt < AI_MAX_ATTEMPTS ? ' — backing off' : ' — giving up'}`,
      );
    } catch (error) {
      lastRes = null;
      console.warn(
        `[news/ai] ${path} network error (attempt ${attempt}/${AI_MAX_ATTEMPTS})`,
        error,
      );
    }
    if (attempt < AI_MAX_ATTEMPTS) {
      await backoffDelay(attempt, lastRes?.status);
    }
  }
  return lastRes;
}

// ── Response-shape parsing ─────────────────────────────────────────────────
//
// The proxy's envelope is `{ message, raw, usage }`: `message.content` is its
// NORMALIZED answer — a plain string for chat models, an array of parts for
// reasoning models (`[{type:'thinking'}, {type:'text'}]`) — and `raw` is the
// provider's untouched payload.
//
// We used to read `message.content` and nothing else, so every response whose
// normalization came back empty was indistinguishable from a dead provider.
// Prod showed two such families, both on `gpt_oss_120b`:
//
//   * `keys=message,raw,usage reason=none content=string(0)` (2026-09-13) —
//     the normalized field is an empty STRING while `raw` still carries the
//     provider payload we never looked at.
//   * `parts[1] types=thinking thinkingChars=1515` (2026-08-14) — a lone
//     reasoning part: the model spent its whole output budget thinking.
//
// Both surfaced downstream as `[cluster-*] genText returned null … AI proxy
// down/rate-limited`, an assertion nothing in the 200 response supported. So:
// look in every field an answer can legitimately arrive in (including `raw`,
// in each upstream API's shape), and when there genuinely is no answer, say
// WHICH of the three causes it was.

interface ContentPart {
  type?: string;
  text?: string;
  thinking?: string;
  reasoning?: string;
  content?: unknown;
}

/** The proxy envelope, plus the fields sibling clients have been seen to use. */
interface ProxyEnvelope {
  message?: { content?: unknown };
  content?: unknown;
  response?: unknown;
  text?: unknown;
  output_text?: unknown;
  raw?: unknown;
  finish_reason?: string;
  stop_reason?: string;
}

/** The provider payload under `raw`, in the shapes the upstream APIs use. */
interface RawPayload {
  choices?: {
    message?: { content?: unknown };
    delta?: { content?: unknown };
    text?: unknown;
  }[];
  content?: unknown;
  output?: { content?: unknown }[];
  output_text?: unknown;
  candidates?: { content?: { parts?: unknown } }[];
  message?: { content?: unknown };
  response?: unknown;
}

/**
 * Part types that carry a model's REASONING, never its answer. Their text is
 * counted (so the diagnostics can say "it thought but never answered") and
 * never returned: a chain of thought is not publishable copy, and handing it
 * back would print raw reasoning on the story page.
 */
const REASONING_PART_TYPES = new Set([
  'thinking',
  'reasoning',
  'redacted_thinking',
  'reasoning_content',
  'thought',
]);

type ExtractCause =
  /** Real text was found. */
  | 'ok'
  /** 200 carrying reasoning but no answer — the model ran out of output budget
   *  inside its thinking block. Worth retrying with a bigger budget. */
  | 'thinking-only'
  /** 200 whose answer field is present and genuinely empty (content filter,
   *  refusal, zero-token completion). Worth one retry; may just repeat. */
  | 'provider-empty'
  /** 200 with no field we recognise as an answer. NOT worth retrying — the
   *  same shape comes back — and a signal the proxy's envelope changed. */
  | 'unrecognized-shape';

interface Extracted {
  text: string;
  /** Which field the text came from — a breadcrumb when it wasn't the usual
   *  one, so a proxy-side normalization regression is visible in telemetry. */
  source: string;
  cause: ExtractCause;
  thinkingChars: number;
}

interface Harvest {
  text: string;
  thinking: number;
}

const EMPTY_HARVEST: Harvest = { text: '', thinking: 0 };

/**
 * Pull answer text (and count reasoning characters) out of one `content`
 * value, which may be a string, an array of parts, a single part object, or a
 * part whose own `content` nests another of those.
 */
function harvest(value: unknown, depth = 0): Harvest {
  if (depth > 4) return EMPTY_HARVEST;
  if (typeof value === 'string') return { text: value, thinking: 0 };
  if (Array.isArray(value)) {
    let text = '';
    let thinking = 0;
    for (const entry of value) {
      const got = harvest(entry, depth + 1);
      text += got.text;
      thinking += got.thinking;
    }
    return { text, thinking };
  }
  if (typeof value === 'object' && value !== null) {
    const part = value as ContentPart;
    if (part.type !== undefined && REASONING_PART_TYPES.has(part.type)) {
      // Providers spell the trace differently: `thinking` (Anthropic format),
      // `reasoning` (OpenAI-compatible gateways), or plain `text`/`content`
      // carried under a reasoning type. Count it; never return it.
      const trace =
        part.thinking ??
        part.reasoning ??
        part.text ??
        (typeof part.content === 'string' ? part.content : undefined);
      return {
        text: '',
        thinking: typeof trace === 'string' ? trace.length : 0,
      };
    }
    if (typeof part.text === 'string') return { text: part.text, thinking: 0 };
    if (part.content !== undefined) return harvest(part.content, depth + 1);
  }
  return EMPTY_HARVEST;
}

/** Answer-bearing fields of the provider payload, in each upstream API's shape.
 *  Only consulted once the proxy's own normalized fields come back empty. */
function rawCandidates(raw: unknown): [string, unknown][] {
  let value = raw;
  if (typeof value === 'string') {
    try {
      value = JSON.parse(value);
    } catch {
      return [];
    }
  }
  if (typeof value !== 'object' || value === null) return [];
  const payload = value as RawPayload;
  const out: [string, unknown][] = [];
  // OpenAI chat completions — and every OpenAI-compatible gateway, which is
  // how `gpt_oss_120b` is reached.
  for (const [i, choice] of (payload.choices ?? []).entries()) {
    if (typeof choice !== 'object' || choice === null) continue;
    out.push([`raw.choices[${String(i)}].message.content`, choice.message?.content]);
    out.push([`raw.choices[${String(i)}].delta.content`, choice.delta?.content]);
    out.push([`raw.choices[${String(i)}].text`, choice.text]);
  }
  // Anthropic messages: a top-level parts array.
  out.push(['raw.content', payload.content]);
  // OpenAI Responses API.
  out.push(['raw.output_text', payload.output_text]);
  for (const [i, item] of (payload.output ?? []).entries()) {
    if (typeof item !== 'object' || item === null) continue;
    out.push([`raw.output[${String(i)}].content`, item.content]);
  }
  // Google generateContent.
  for (const [i, candidate] of (payload.candidates ?? []).entries()) {
    if (typeof candidate !== 'object' || candidate === null) continue;
    out.push([
      `raw.candidates[${String(i)}].content.parts`,
      candidate.content?.parts,
    ]);
  }
  out.push(['raw.message.content', payload.message?.content]);
  out.push(['raw.response', payload.response]);
  return out;
}

/**
 * Find the model's answer anywhere it can legitimately be, and when there is
 * none, classify WHY. Never throws; never returns reasoning as the answer.
 */
export function extractText(data: unknown): Extracted {
  const envelope: ProxyEnvelope =
    typeof data === 'object' && data !== null ? data : {};
  const candidates: [string, unknown][] = [
    ['message.content', envelope.message?.content],
    ['content', envelope.content],
    ['response', envelope.response],
    ['text', envelope.text],
    ['output_text', envelope.output_text],
    ...rawCandidates(envelope.raw),
  ];
  let thinkingChars = 0;
  let sawAnswerField = false;
  for (const [source, value] of candidates) {
    if (value === undefined || value === null) continue;
    sawAnswerField = true;
    const got = harvest(value);
    thinkingChars += got.thinking;
    const text = got.text.trim();
    if (text) return { text, source, cause: 'ok', thinkingChars };
  }
  const cause: ExtractCause =
    thinkingChars > 0
      ? 'thinking-only'
      : sawAnswerField
        ? 'provider-empty'
        : 'unrecognized-shape';
  return { text: '', source: 'none', cause, thinkingChars };
}

/**
 * One-line description of a 200 response that yielded no usable text, for the
 * telemetry message. Reports the top-level keys, the stop/finish reason, the
 * shape of `content`, and — when it is a parts array — which part types came
 * back and how much `thinking` there was, plus the keys of the provider
 * payload we fell through to. Never throws and never logs message text.
 */
function describeEmptyBody(data: unknown): string {
  try {
    const d = data as Record<string, unknown>;
    const keys = Object.keys(d ?? {})
      .slice(0, 8)
      .join(',');
    const body = (d ?? {}) as ProxyEnvelope;
    const content = body.message?.content ?? body.content;
    const reason = body.finish_reason ?? body.stop_reason ?? 'none';
    let shape: string;
    if (typeof content === 'string') {
      shape = `string(${String(content.length)})`;
    } else if (Array.isArray(content)) {
      const parts = content as ContentPart[];
      const types = [...new Set(parts.map((p) => p?.type ?? '?'))].join('|');
      const thinking = parts.reduce(
        (n, p) => n + (typeof p?.thinking === 'string' ? p.thinking.length : 0),
        0,
      );
      shape = `parts[${String(parts.length)}] types=${types} thinkingChars=${String(thinking)}`;
    } else {
      shape = content === undefined ? 'missing' : typeof content;
    }
    // `raw` is where a real answer hid while `message.content` was empty, so
    // name its keys: that is what tells a proxy-normalization bug apart from a
    // provider that genuinely returned nothing.
    const raw = body.raw;
    const rawShape =
      raw === undefined
        ? ''
        : ` raw=${
            typeof raw === 'object' && raw !== null
              ? `keys(${Object.keys(raw).slice(0, 6).join('|')})`
              : typeof raw
          }`;
    return `keys=${keys} reason=${reason} content=${shape}${rawShape}`;
  } catch {
    return 'undescribable';
  }
}

/**
 * Models that emit `thinking` blocks out of a SHARED output budget, and what
 * that costs us.
 *
 * `deepseek_v4_flash` reaches DeepSeek's Anthropic-format gateway
 * (`api.deepseek.com/anthropic/v1/messages`). Two facts combine badly there:
 *
 *   1. `max_tokens` is the TOTAL output budget — thinking blocks count against
 *      it, exactly as in Anthropic's own API.
 *   2. Thinking is force-enabled for the model and CANNOT be turned off:
 *      ugly-bot's providerCatalog pins `ANTHROPIC_EFFORT_THINKING` on every
 *      DeepSeek entry, and the gateway silently ignores `budget_tokens`, so
 *      there is no way to bound the thinking half from the request.
 *
 * `gpt_oss_120b` is the same trap by a different route: gpt-oss emits a
 * harmony reasoning preamble before its visible text, out of the same
 * `maxTokens` budget. That is already documented at the ad-gate call site
 * (`AD_DETECTION_MAX_TOKENS`, where a budget of 10 returned empty content on
 * EVERY call) and it is what produced `types=thinking thinkingChars=1515`
 * here. It is missing `thinkingSupport` in the model catalog, so there is no
 * effort knob to turn — only headroom.
 *
 * So a small `maxTokens` is spent entirely inside the reasoning block and the
 * model is cut off before it emits a single `text` part. `extractText` then
 * correctly finds no answer and reports `cause=thinking-only`.
 *
 * The caller's `maxTokens` means "how much TEXT I want". Add the reasoning
 * allowance on top of it rather than making every call site remember this, and
 * hold effort at `low` where the model HAS an effort knob — headroom alone
 * still overflows if the default effort drifts up. Unused budget is not billed
 * (output tokens are charged as generated), so a generous reserve is free.
 */
const THINKING_RESERVE_MODELS = new Set([
  'deepseek_v4_flash',
  'deepseek_v4_pro',
  'gpt_oss_120b',
]);
/** Subset of the above that accepts `reasoningEffort` (has `thinkingSupport`
 *  in the framework's model catalog). gpt-oss does not, so it gets headroom
 *  only — sending an effort it cannot honour buys nothing. */
const LOW_EFFORT_MODELS = new Set(['deepseek_v4_flash', 'deepseek_v4_pro']);
const THINKING_TOKEN_RESERVE = 2048;

/**
 * Attempts allowed for a 200 that parsed but carried no answer. This is NOT
 * the transport retry (`postAi` handles 429/5xx/network); it is the "provider
 * answered, with nothing" case, which used to be a hard drop. The retry buys
 * another `THINKING_TOKEN_RESERVE` of output budget, so a response truncated
 * inside its reasoning block gets room to actually answer the second time
 * instead of re-rolling the same dice. `pace()` already spaces consecutive
 * proxy calls by MIN_CALL_GAP_MS, which is the backoff between them.
 */
const EMPTY_COMPLETION_ATTEMPTS = 2;

/** Owner-billed text generation via the ugly.bot AI proxy. */
export async function genText(
  messages: ChatMessage[],
  opts: { model: string; temperature?: number; maxTokens?: number },
): Promise<string | null> {
  const { baseUrl, token } = aiProxy();
  if (!token) {
    console.warn('[news/ai] genText: AI_PROXY_TOKEN not set');
    return null;
  }
  const reserves = THINKING_RESERVE_MODELS.has(opts.model);
  const lowEffort = LOW_EFFORT_MODELS.has(opts.model);
  for (let attempt = 1; attempt <= EMPTY_COMPLETION_ATTEMPTS; attempt++) {
    // Base reserve for models that think, plus one more reserve per retry —
    // an empty completion is most often a budget that never reached the text.
    const boost =
      (reserves ? THINKING_TOKEN_RESERVE : 0) +
      (attempt - 1) * THINKING_TOKEN_RESERVE;
    const maxTokens =
      opts.maxTokens !== undefined ? opts.maxTokens + boost : undefined;
    const res = await postAi(baseUrl, '/text', token, {
      model: opts.model,
      messages,
      userId: 'uglyBot',
      options: {
        ...(opts.temperature !== undefined
          ? { temperature: opts.temperature }
          : {}),
        ...(maxTokens !== undefined ? { maxTokens } : {}),
        ...(lowEffort ? { reasoningEffort: 'low' as const } : {}),
      },
    });
    if (!res) {
      console.warn('[news/ai] genText: no response after retries');
      return null;
    }
    if (!res.ok) {
      console.warn(
        `[news/ai] genText ${res.status}: ${(await res.text().catch(() => '')).slice(0, 200)}`,
      );
      return null;
    }
    let data: unknown;
    try {
      data = await res.json();
    } catch (error) {
      console.warn('[news/ai] genText: failed to parse response body', error);
      return null;
    }
    const got = extractText(data);
    if (got.text) {
      if (got.source !== 'message.content') {
        // The proxy's normalized field was empty and the answer was elsewhere.
        // Worth one line: it means the envelope moved, not that anything broke.
        console.warn(
          `[news/ai] genText: answer recovered from ${got.source} (model=${opts.model}) — message.content held no text`,
        );
      }
      return got.text;
    }
    // A 200 with no usable text used to return null with no log at all, then
    // (from 2026-07) with a shape descriptor but no verdict. Say which of the
    // three causes it was, so nobody has to guess "AI proxy down" again.
    console.warn(
      `[news/ai] genText: ${res.status} OK but no text content (model=${opts.model}) cause=${got.cause} attempt=${String(attempt)}/${String(EMPTY_COMPLETION_ATTEMPTS)} shape=${describeEmptyBody(data)}`,
    );
    // An unrecognised envelope will be unrecognised again — retrying it only
    // spends money. Empty/thinking-only responses get the bigger budget.
    if (got.cause === 'unrecognized-shape') return null;
  }
  return null;
}

/** Owner-billed image generation (returns a URL or data URI), or null. */
export async function genImage(
  prompt: string,
  opts?: { model?: ImageGenModel; negative?: string },
): Promise<string | null> {
  const { baseUrl, token } = aiProxy();
  if (!token) {
    console.warn('[news/ai] genImage: AI_PROXY_TOKEN not set');
    return null;
  }
  const fullPrompt = opts?.negative
    ? `${prompt}\n\nAvoid: ${opts.negative}`
    : prompt;
  const res = await postAi(baseUrl, '/image', token, {
    model: opts?.model ?? 'flux_1_dev',
    prompt: fullPrompt,
    userId: 'uglyBot',
    options: { aspectRatio: 'landscape_16_9' },
  });
  if (!res) {
    console.warn('[news/ai] genImage: no response after retries');
    return null;
  }
  if (!res.ok) {
    console.warn(
      `[news/ai] genImage ${res.status}: ${(await res.text().catch(() => '')).slice(0, 200)}`,
    );
    return null;
  }
  try {
    const data = (await res.json()) as {
      url?: string;
      base64?: string;
      mime?: string;
    };
    if (data.url) return data.url;
    if (data.base64)
      return await hostGeneratedImage(data.base64, data.mime ?? 'image/png');
    // Same silent-null trap as genText: a 200 carrying neither url nor base64.
    console.warn(
      `[news/ai] genImage: ${res.status} OK but no url/base64 in response`,
    );
    return null;
  } catch (error) {
    console.warn('[news/ai] genImage: failed to parse response', error);
    return null;
  }
}

/**
 * "The Ugly Press" house illustration for a news subject (article title or
 * cluster headline). Every generated news image shares the paper's editorial
 * newspaper-brutalist look so the feed reads as one publication, not a grab-bag
 * of stock photography. Used at DISPLAY-PROMOTION points only (qualifying story
 * clusters + their Ugly Take) — never eagerly per scraped article — so we spend
 * one generation per shown story instead of one per article.
 */
export async function generateUglyPressImage(
  subject: string,
  category: NewsCategory,
): Promise<string | null> {
  const prompt = [
    `Editorial illustration for a satirical newspaper, "The Ugly Press", depicting: ${subject}.`,
    'Style: bold mid-century editorial newspaper illustration, screen-printed / risograph look, heavy ink linework, visible halftone dot texture, slightly distressed newsprint grain.',
    'Limited palette: warm cream newsprint background, deep ink black, and a single vermilion red accent.',
    `Conceptual and a little wry, fitting the ${category} desk. Strong composition, high contrast, flat shapes.`,
    'Absolutely no text, words, letters, numbers, captions, or logos.',
  ].join(' ');
  const negative =
    'text, words, letters, numbers, captions, watermark, signature, logo, photorealistic, 3d render, glossy, low quality, blurry';
  return genImage(prompt, { model: 'flux_1_dev', negative });
}

// The AI image proxy returns raw base64 for models that don't self-host (e.g.
// flux_1_dev). Persisting that as a `data:` URI bloats every `file` doc by
// ~300KB and breaks the daily email (Gmail clips messages >~102KB, and clients
// strip `data:` images). Re-host it in the app's own public R2 bucket —
// content-addressed by sha256 so identical renders dedupe — and return the
// same-origin URL, exactly like podcast audio / the TTS cache. On any storage
// failure we drop the (decorative) image rather than fall back to a data URI.
async function hostGeneratedImage(
  base64: string,
  mime: string,
): Promise<string | null> {
  try {
    const bytes = base64ToBytes(base64);
    // Copy into a plain ArrayBuffer so digest() accepts it (Uint8Array may be
    // backed by SharedArrayBuffer, which isn't a BufferSource).
    const ab = new ArrayBuffer(bytes.byteLength);
    new Uint8Array(ab).set(bytes);
    const digest = await crypto.subtle.digest('SHA-256', ab);
    const hash = [...new Uint8Array(digest)]
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
    const ext = mime.includes('png')
      ? 'png'
      : mime.includes('webp')
        ? 'webp'
        : 'jpg';
    const key = `gen-images/${hash}.${ext}`;
    const storage = getAdapter().storage;
    await storage.put('public', key, bytes, mime);
    return storage.url('public', key);
  } catch (error) {
    console.warn(
      '[news/ai] genImage: R2 upload failed — dropping image',
      error,
    );
    return null;
  }
}

// Semantic embeddings (512-dim, matching the `file` collection's declared
// vector { dimensions: 512 } column) route through ugly.bot's `embedGen` proxy
// — NOT a direct OpenAI call. embedGen runs OpenAI text-embedding-3-small with
// the key held centrally in ugly.bot, and meters/bills the call against the
// app's account (same platform pattern as bahai-app). `createEmbeddingClient`
// from the workers adapter is a thin fetch wrapper over `uglyBotRequest`.
const EMBED_DIMS = 512;
let embeddingClient: ReturnType<typeof createEmbeddingClient> | null = null;

/** ugly.bot embedGen embedding for feed ranking / search (512-dim), or null. */
export async function embed(text: string): Promise<number[] | null> {
  const input = text.trim().slice(0, 8000) || ' ';
  try {
    embeddingClient ??= createEmbeddingClient();
    const vec = await embeddingClient.embed(input, { dimensions: EMBED_DIMS });
    return vec ?? null;
  } catch (error) {
    console.warn('[news/ai] embed failed', error);
    return null;
  }
}

/** ~4 chars/token heuristic truncation (ported from ugly.bot Helper). */
export function truncateToApproximateTokens(
  text: string,
  maxTokens: number,
): string {
  const maxChars = maxTokens * 4;
  return text.length <= maxChars ? text : text.slice(0, maxChars);
}
