// Emits the registry the extension bundles, from the committed source seeds.
// Generated output IS committed so the extension builds without a DB, and so
// registry changes show up in review as a readable diff.
//
// Run with tsx (a devDependency) so it can import the shared TS directly:
//   pnpm run gen:extension-registry
//
// The ~3,875-row domainBias table is deliberately NOT included: it is not
// committed to this repo. Adding it later means extending this generator.
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildRegistryIndex } from '../shared/news/fact-registry';
import { newsSourceSeeds } from '../shared/news/sourceBias';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const index = buildRegistryIndex(newsSourceSeeds);
const sorted = Object.fromEntries(
  Object.entries(index).sort(([a], [b]) => a.localeCompare(b)),
);

const out = join(root, 'extension', 'src', 'generated', 'registry.ts');
await mkdir(dirname(out), { recursive: true });
await writeFile(
  out,
  `// GENERATED by scripts/gen-extension-registry.ts — do not edit by hand.\n` +
    `// Regenerate: pnpm run gen:extension-registry\n` +
    `import type { RegistryIndex } from '../../../shared/news/fact-registry';\n\n` +
    `export const BUNDLED_REGISTRY: RegistryIndex = ${JSON.stringify(sorted, null, 2)};\n`,
  'utf8',
);

console.log(
  `registry → ${out} (${String(Object.keys(sorted).length)} domains, ${String(newsSourceSeeds.length)} sources)`,
);
