import type { Bias, Factuality } from './schemas';

// ============================================================================
// Source bias / factuality / ownership seed.
//
// Curated for the outlets WE ingest (shared/news/types.ts) — not a redistribution
// of any third-party database. `bias` + `biasScore` are our reading of the public
// AllSides / Ad Fontes / Media Bias-Fact Check charts; `factuality` blends their
// reliability ratings; `owner` is from Wikidata/company filings.
//
// `biasScore` is the −6 (far left) .. +6 (far right) position used to derive the
// three-way coverage bucket (see toBiasBucket in server/news/cluster-logic).
//
// Feeds with no entry here (e.g. the Google News aggregators) are treated as
// UNRATED: they still cluster and display, but don't move the bias bar.
// ============================================================================

export interface NewsSourceSeed {
  id: string;
  name: string;
  homepage: string | null;
  domains: string[];
  feedIds: string[];
  bias: Bias;
  biasScore: number;
  factuality: Factuality;
  owner: string | null;
  country: string | null;
}

export const newsSourceSeeds: NewsSourceSeed[] = [
  // ─── Center / center-ish ──────────────────────────────────────────────────
  {
    id: 'thehill',
    name: 'The Hill',
    homepage: 'https://thehill.com',
    domains: ['thehill.com'],
    feedIds: ['thehill'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Nexstar Media Group',
    country: 'US',
  },
  {
    id: 'bbc',
    name: 'BBC News',
    homepage: 'https://www.bbc.com/news',
    domains: ['bbc.com', 'bbc.co.uk'],
    feedIds: ['bbc_world'],
    bias: 'center',
    biasScore: -0.5,
    factuality: 'high',
    owner: 'BBC (UK public)',
    country: 'UK',
  },
  {
    id: 'dw',
    name: 'Deutsche Welle',
    homepage: 'https://www.dw.com',
    domains: ['dw.com'],
    feedIds: ['dw_world'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'ARD (German public)',
    country: 'DE',
  },
  {
    id: 'cnbc',
    name: 'CNBC',
    homepage: 'https://www.cnbc.com',
    domains: ['cnbc.com'],
    feedIds: ['cnbc'],
    bias: 'center',
    biasScore: 0.5,
    factuality: 'high',
    owner: 'NBCUniversal (Comcast)',
    country: 'US',
  },
  {
    id: 'marketwatch',
    name: 'MarketWatch',
    homepage: 'https://www.marketwatch.com',
    domains: ['marketwatch.com'],
    feedIds: ['marketwatch'],
    bias: 'center',
    biasScore: 0.5,
    factuality: 'high',
    owner: 'Dow Jones (News Corp)',
    country: 'US',
  },
  {
    id: 'fortune',
    name: 'Fortune',
    homepage: 'https://fortune.com',
    domains: ['fortune.com'],
    feedIds: ['fortune'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Fortune Media',
    country: 'US',
  },
  {
    id: 'forbes',
    name: 'Forbes',
    homepage: 'https://www.forbes.com',
    domains: ['forbes.com'],
    feedIds: ['forbes_business'],
    bias: 'center',
    biasScore: 1,
    factuality: 'mixed',
    owner: 'Forbes Media',
    country: 'US',
  },
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    homepage: 'https://techcrunch.com',
    domains: ['techcrunch.com'],
    feedIds: ['techcrunch'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Yahoo (Apollo)',
    country: 'US',
  },
  {
    id: 'theverge',
    name: 'The Verge',
    homepage: 'https://www.theverge.com',
    domains: ['theverge.com'],
    feedIds: ['theverge'],
    bias: 'lean-left',
    biasScore: -1,
    factuality: 'high',
    owner: 'Vox Media',
    country: 'US',
  },
  {
    id: 'arstechnica',
    name: 'Ars Technica',
    homepage: 'https://arstechnica.com',
    domains: ['arstechnica.com'],
    feedIds: ['arstechnica', 'arstechnica_science'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Condé Nast',
    country: 'US',
  },
  {
    id: 'engadget',
    name: 'Engadget',
    homepage: 'https://www.engadget.com',
    domains: ['engadget.com'],
    feedIds: ['engadget'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Yahoo (Apollo)',
    country: 'US',
  },
  {
    id: 'sciencedaily',
    name: 'ScienceDaily',
    homepage: 'https://www.sciencedaily.com',
    domains: ['sciencedaily.com'],
    feedIds: ['sciencedaily'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'ScienceDaily LLC',
    country: 'US',
  },
  {
    id: 'physorg',
    name: 'Phys.org',
    homepage: 'https://phys.org',
    domains: ['phys.org'],
    feedIds: ['physorg'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Science X',
    country: 'US',
  },
  {
    id: 'variety',
    name: 'Variety',
    homepage: 'https://variety.com',
    domains: ['variety.com'],
    feedIds: ['variety'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Penske Media',
    country: 'US',
  },
  {
    id: 'hollywoodreporter',
    name: 'The Hollywood Reporter',
    homepage: 'https://www.hollywoodreporter.com',
    domains: ['hollywoodreporter.com'],
    feedIds: ['hollywoodreporter'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Penske Media',
    country: 'US',
  },
  {
    id: 'pitchfork',
    name: 'Pitchfork',
    homepage: 'https://pitchfork.com',
    domains: ['pitchfork.com'],
    feedIds: ['pitchfork'],
    bias: 'lean-left',
    biasScore: -1,
    factuality: 'high',
    owner: 'Condé Nast',
    country: 'US',
  },
  {
    id: 'espn',
    name: 'ESPN',
    homepage: 'https://www.espn.com',
    domains: ['espn.com'],
    feedIds: ['espn'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'The Walt Disney Company',
    country: 'US',
  },

  // ─── Left ─────────────────────────────────────────────────────────────────
  {
    id: 'npr',
    name: 'NPR',
    homepage: 'https://www.npr.org',
    domains: ['npr.org'],
    feedIds: ['npr_politics'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'NPR (US public)',
    country: 'US',
  },
  {
    id: 'nbcnews',
    name: 'NBC News',
    homepage: 'https://www.nbcnews.com',
    domains: ['nbcnews.com'],
    feedIds: ['nbcnews'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'NBCUniversal (Comcast)',
    country: 'US',
  },
  {
    id: 'nyt',
    name: 'The New York Times',
    homepage: 'https://www.nytimes.com',
    domains: ['nytimes.com'],
    feedIds: ['nyt_world'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'The New York Times Company',
    country: 'US',
  },
  {
    id: 'aljazeera',
    name: 'Al Jazeera',
    homepage: 'https://www.aljazeera.com',
    domains: ['aljazeera.com'],
    feedIds: ['aljazeera'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'mixed',
    owner: 'Al Jazeera Media Network (Qatar)',
    country: 'QA',
  },
  {
    id: 'wired',
    name: 'Wired',
    homepage: 'https://www.wired.com',
    domains: ['wired.com'],
    feedIds: ['wired'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'Condé Nast',
    country: 'US',
  },
  {
    id: 'scientificamerican',
    name: 'Scientific American',
    homepage: 'https://www.scientificamerican.com',
    domains: ['scientificamerican.com'],
    feedIds: ['scientificamerican'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'Springer Nature',
    country: 'US',
  },
  {
    id: 'guardian',
    name: 'The Guardian',
    homepage: 'https://www.theguardian.com',
    domains: ['theguardian.com'],
    feedIds: ['guardian_us', 'guardian_world'],
    bias: 'left',
    biasScore: -2.5,
    factuality: 'high',
    owner: 'Guardian Media Group',
    country: 'UK',
  },
  {
    id: 'rollingstone',
    name: 'Rolling Stone',
    homepage: 'https://www.rollingstone.com',
    domains: ['rollingstone.com'],
    feedIds: ['rollingstone'],
    bias: 'left',
    biasScore: -2.5,
    factuality: 'mixed',
    owner: 'Penske Media',
    country: 'US',
  },
  {
    id: 'vox',
    name: 'Vox',
    homepage: 'https://www.vox.com',
    domains: ['vox.com'],
    feedIds: ['vox'],
    bias: 'left',
    biasScore: -3,
    factuality: 'high',
    owner: 'Vox Media',
    country: 'US',
  },
  {
    id: 'huffpost',
    name: 'HuffPost',
    homepage: 'https://www.huffpost.com',
    domains: ['huffpost.com'],
    feedIds: ['huffpost_politics'],
    bias: 'left',
    biasScore: -3,
    factuality: 'mixed',
    owner: 'BuzzFeed Inc.',
    country: 'US',
  },
  {
    id: 'thenation',
    name: 'The Nation',
    homepage: 'https://www.thenation.com',
    domains: ['thenation.com'],
    feedIds: ['thenation'],
    bias: 'left',
    biasScore: -3.5,
    factuality: 'mixed',
    owner: 'The Nation Company',
    country: 'US',
  },

  // ─── Right ────────────────────────────────────────────────────────────────
  {
    id: 'nationalreview',
    name: 'National Review',
    homepage: 'https://www.nationalreview.com',
    domains: ['nationalreview.com'],
    feedIds: ['nationalreview'],
    bias: 'right',
    biasScore: 3,
    factuality: 'high',
    owner: 'National Review Institute',
    country: 'US',
  },
  {
    id: 'washingtonexaminer',
    name: 'Washington Examiner',
    homepage: 'https://www.washingtonexaminer.com',
    domains: ['washingtonexaminer.com'],
    feedIds: ['washingtonexaminer'],
    bias: 'right',
    biasScore: 3,
    factuality: 'mixed',
    owner: 'Clarity Media Group',
    country: 'US',
  },
  {
    id: 'nypost',
    name: 'New York Post',
    homepage: 'https://nypost.com',
    domains: ['nypost.com'],
    feedIds: ['nypost'],
    bias: 'right',
    biasScore: 3,
    factuality: 'mixed',
    owner: 'News Corp',
    country: 'US',
  },
  {
    id: 'foxnews',
    name: 'Fox News',
    homepage: 'https://www.foxnews.com',
    domains: ['foxnews.com'],
    feedIds: ['foxnews_politics'],
    bias: 'right',
    biasScore: 3.5,
    factuality: 'mixed',
    owner: 'Fox Corporation',
    country: 'US',
  },
  {
    id: 'dailywire',
    name: 'The Daily Wire',
    homepage: 'https://www.dailywire.com',
    domains: ['dailywire.com'],
    feedIds: ['dailywire'],
    bias: 'far-right',
    biasScore: 4.5,
    factuality: 'mixed',
    owner: 'The Daily Wire',
    country: 'US',
  },

  // ─── Expansion 2026-06-30 ─────────────────────────────────────────────────
  // Center
  {
    id: 'pbs',
    name: 'PBS NewsHour',
    homepage: 'https://www.pbs.org/newshour',
    domains: ['pbs.org'],
    feedIds: ['pbs'],
    bias: 'center',
    biasScore: -0.5,
    factuality: 'high',
    owner: 'PBS (US public)',
    country: 'US',
  },
  {
    id: 'csmonitor',
    name: 'Christian Science Monitor',
    homepage: 'https://www.csmonitor.com',
    domains: ['csmonitor.com'],
    feedIds: ['csmonitor'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Christian Science Publishing Society',
    country: 'US',
  },
  {
    id: 'newsweek',
    name: 'Newsweek',
    homepage: 'https://www.newsweek.com',
    domains: ['newsweek.com'],
    feedIds: ['newsweek'],
    bias: 'center',
    biasScore: 0.5,
    factuality: 'mixed',
    owner: 'Newsweek LLC',
    country: 'US',
  },
  {
    id: 'france24',
    name: 'France 24',
    homepage: 'https://www.france24.com',
    domains: ['france24.com'],
    feedIds: ['france24'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'France Médias Monde (French public)',
    country: 'FR',
  },
  {
    id: 'skynews',
    name: 'Sky News',
    homepage: 'https://news.sky.com',
    domains: ['skynews.com', 'sky.com'],
    feedIds: ['skynews_world'],
    bias: 'center',
    biasScore: -0.5,
    factuality: 'high',
    owner: 'Sky Group (Comcast)',
    country: 'UK',
  },
  {
    id: 'yahoofinance',
    name: 'Yahoo Finance',
    homepage: 'https://finance.yahoo.com',
    domains: ['finance.yahoo.com', 'yahoo.com'],
    feedIds: ['yahoofinance'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Yahoo (Apollo)',
    country: 'US',
  },
  {
    id: 'businessinsider',
    name: 'Business Insider',
    homepage: 'https://www.businessinsider.com',
    domains: ['businessinsider.com'],
    feedIds: ['businessinsider'],
    bias: 'lean-left',
    biasScore: -1,
    factuality: 'mixed',
    owner: 'Axel Springer SE',
    country: 'US',
  },
  {
    id: 'theregister',
    name: 'The Register',
    homepage: 'https://www.theregister.com',
    domains: ['theregister.com'],
    feedIds: ['theregister'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Situation Publishing',
    country: 'UK',
  },
  {
    id: 'venturebeat',
    name: 'VentureBeat',
    homepage: 'https://venturebeat.com',
    domains: ['venturebeat.com'],
    feedIds: ['venturebeat'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'VentureBeat',
    country: 'US',
  },
  {
    id: 'hackernews',
    name: 'Hacker News',
    homepage: 'https://news.ycombinator.com',
    domains: ['ycombinator.com'],
    feedIds: ['hackernews'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Y Combinator',
    country: 'US',
  },
  {
    id: '404media',
    name: '404 Media',
    homepage: 'https://www.404media.co',
    domains: ['404media.co'],
    feedIds: ['404media'],
    bias: 'lean-left',
    biasScore: -1,
    factuality: 'high',
    owner: '404 Media',
    country: 'US',
  },
  {
    id: 'nature',
    name: 'Nature',
    homepage: 'https://www.nature.com',
    domains: ['nature.com'],
    feedIds: ['nature'],
    bias: 'center',
    biasScore: 0,
    factuality: 'very-high',
    owner: 'Springer Nature',
    country: 'UK',
  },
  {
    id: 'quanta',
    name: 'Quanta Magazine',
    homepage: 'https://www.quantamagazine.org',
    domains: ['quantamagazine.org'],
    feedIds: ['quanta'],
    bias: 'center',
    biasScore: 0,
    factuality: 'very-high',
    owner: 'Simons Foundation',
    country: 'US',
  },
  {
    id: 'space',
    name: 'Space.com',
    homepage: 'https://www.space.com',
    domains: ['space.com'],
    feedIds: ['space'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Future plc',
    country: 'US',
  },
  {
    id: 'deadline',
    name: 'Deadline',
    homepage: 'https://deadline.com',
    domains: ['deadline.com'],
    feedIds: ['deadline'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Penske Media',
    country: 'US',
  },
  {
    id: 'ign',
    name: 'IGN',
    homepage: 'https://www.ign.com',
    domains: ['ign.com'],
    feedIds: ['ign'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Ziff Davis',
    country: 'US',
  },
  {
    id: 'stereogum',
    name: 'Stereogum',
    homepage: 'https://www.stereogum.com',
    domains: ['stereogum.com'],
    feedIds: ['stereogum'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Brooklyn Vegan / SpinMedia',
    country: 'US',
  },
  // Left
  {
    id: 'abcnews',
    name: 'ABC News',
    homepage: 'https://abcnews.go.com',
    domains: ['abcnews.go.com', 'go.com'],
    feedIds: ['abcnews'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'The Walt Disney Company',
    country: 'US',
  },
  {
    id: 'cbsnews',
    name: 'CBS News',
    homepage: 'https://www.cbsnews.com',
    domains: ['cbsnews.com'],
    feedIds: ['cbsnews'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'Paramount Global',
    country: 'US',
  },
  {
    id: 'theconversation',
    name: 'The Conversation',
    homepage: 'https://theconversation.com',
    domains: ['theconversation.com'],
    feedIds: ['theconversation'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'The Conversation Trust',
    country: 'US',
  },
  {
    id: 'independent',
    name: 'The Independent',
    homepage: 'https://www.independent.co.uk',
    domains: ['independent.co.uk'],
    feedIds: ['independent_world'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'Independent Digital News & Media',
    country: 'UK',
  },
  {
    id: 'avclub',
    name: 'The A.V. Club',
    homepage: 'https://www.avclub.com',
    domains: ['avclub.com'],
    feedIds: ['avclub'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'mixed',
    owner: 'Paste Media',
    country: 'US',
  },
  {
    id: 'cnn',
    name: 'CNN',
    homepage: 'https://www.cnn.com',
    domains: ['cnn.com'],
    feedIds: ['cnn_world'],
    bias: 'left',
    biasScore: -2,
    factuality: 'mixed',
    owner: 'Warner Bros. Discovery',
    country: 'US',
  },
  {
    id: 'newrepublic',
    name: 'The New Republic',
    homepage: 'https://newrepublic.com',
    domains: ['newrepublic.com'],
    feedIds: ['newrepublic'],
    bias: 'left',
    biasScore: -3,
    factuality: 'high',
    owner: 'The New Republic',
    country: 'US',
  },
  {
    id: 'slate',
    name: 'Slate',
    homepage: 'https://slate.com',
    domains: ['slate.com'],
    feedIds: ['slate'],
    bias: 'left',
    biasScore: -3,
    factuality: 'mixed',
    owner: 'The Slate Group',
    country: 'US',
  },
  {
    id: 'intercept',
    name: 'The Intercept',
    homepage: 'https://theintercept.com',
    domains: ['theintercept.com'],
    feedIds: ['intercept'],
    bias: 'left',
    biasScore: -3,
    factuality: 'mixed',
    owner: 'First Look Media',
    country: 'US',
  },
  {
    id: 'motherjones',
    name: 'Mother Jones',
    homepage: 'https://www.motherjones.com',
    domains: ['motherjones.com'],
    feedIds: ['motherjones'],
    bias: 'left',
    biasScore: -3.5,
    factuality: 'high',
    owner: 'Foundation for National Progress',
    country: 'US',
  },
  {
    id: 'salon',
    name: 'Salon',
    homepage: 'https://www.salon.com',
    domains: ['salon.com'],
    feedIds: ['salon'],
    bias: 'left',
    biasScore: -3.5,
    factuality: 'mixed',
    owner: 'Salon Media Group',
    country: 'US',
  },
  {
    id: 'commondreams',
    name: 'Common Dreams',
    homepage: 'https://www.commondreams.org',
    domains: ['commondreams.org'],
    feedIds: ['commondreams'],
    bias: 'left',
    biasScore: -3.5,
    factuality: 'mixed',
    owner: 'Common Dreams',
    country: 'US',
  },
  // Right
  {
    id: 'reason',
    name: 'Reason',
    homepage: 'https://reason.com',
    domains: ['reason.com'],
    feedIds: ['reason'],
    bias: 'lean-right',
    biasScore: 1.5,
    factuality: 'high',
    owner: 'Reason Foundation',
    country: 'US',
  },
  {
    id: 'washingtontimes',
    name: 'The Washington Times',
    homepage: 'https://www.washingtontimes.com',
    domains: ['washingtontimes.com'],
    feedIds: ['washingtontimes'],
    bias: 'right',
    biasScore: 3,
    factuality: 'mixed',
    owner: 'Operations Holdings',
    country: 'US',
  },
  {
    id: 'freebeacon',
    name: 'Washington Free Beacon',
    homepage: 'https://freebeacon.com',
    domains: ['freebeacon.com'],
    feedIds: ['freebeacon'],
    bias: 'right',
    biasScore: 3,
    factuality: 'mixed',
    owner: 'Washington Free Beacon',
    country: 'US',
  },
  {
    id: 'dailycaller',
    name: 'The Daily Caller',
    homepage: 'https://dailycaller.com',
    domains: ['dailycaller.com'],
    feedIds: ['dailycaller'],
    bias: 'right',
    biasScore: 3.5,
    factuality: 'mixed',
    owner: 'The Daily Caller',
    country: 'US',
  },
  {
    id: 'federalist',
    name: 'The Federalist',
    homepage: 'https://thefederalist.com',
    domains: ['thefederalist.com'],
    feedIds: ['federalist'],
    bias: 'right',
    biasScore: 3.5,
    factuality: 'mixed',
    owner: 'FDRLST Media',
    country: 'US',
  },
  {
    id: 'breitbart',
    name: 'Breitbart',
    homepage: 'https://www.breitbart.com',
    domains: ['breitbart.com'],
    feedIds: ['breitbart'],
    bias: 'far-right',
    biasScore: 4.5,
    factuality: 'low',
    owner: 'Breitbart News Network',
    country: 'US',
  },

  // ─── Expansion 2026-07-01 (IDIAP-vetted, verified-live feeds) ─────────────
  // Left / lean-left
  {
    id: 'time',
    name: 'Time',
    homepage: 'https://time.com',
    domains: ['time.com'],
    feedIds: ['time'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'Time USA, LLC',
    country: 'US',
  },
  {
    id: 'latimes',
    name: 'Los Angeles Times',
    homepage: 'https://www.latimes.com',
    domains: ['latimes.com'],
    feedIds: ['latimes'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'Nant Capital (P. Soon-Shiong)',
    country: 'US',
  },
  {
    id: 'theatlantic',
    name: 'The Atlantic',
    homepage: 'https://www.theatlantic.com',
    domains: ['theatlantic.com'],
    feedIds: ['theatlantic'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'Emerson Collective',
    country: 'US',
  },
  {
    id: 'newyorker',
    name: 'The New Yorker',
    homepage: 'https://www.newyorker.com',
    domains: ['newyorker.com'],
    feedIds: ['newyorker'],
    bias: 'left',
    biasScore: -2.5,
    factuality: 'high',
    owner: 'Condé Nast',
    country: 'US',
  },
  {
    id: 'axios',
    name: 'Axios',
    homepage: 'https://www.axios.com',
    domains: ['axios.com'],
    feedIds: ['axios'],
    bias: 'lean-left',
    biasScore: -1,
    factuality: 'high',
    owner: 'Cox Enterprises',
    country: 'US',
  },
  {
    id: 'abc_au',
    name: 'ABC News (Australia)',
    homepage: 'https://www.abc.net.au/news',
    domains: ['abc.net.au'],
    feedIds: ['abc_au'],
    bias: 'lean-left',
    biasScore: -1.5,
    factuality: 'high',
    owner: 'ABC (Australian public)',
    country: 'AU',
  },
  // Center
  {
    id: 'cnet',
    name: 'CNET',
    homepage: 'https://www.cnet.com',
    domains: ['cnet.com'],
    feedIds: ['cnet'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Ziff Davis',
    country: 'US',
  },
  {
    id: 'ft',
    name: 'Financial Times',
    homepage: 'https://www.ft.com',
    domains: ['ft.com'],
    feedIds: ['ft'],
    bias: 'center',
    biasScore: 0,
    factuality: 'high',
    owner: 'Nikkei Inc.',
    country: 'UK',
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg',
    homepage: 'https://www.bloomberg.com',
    domains: ['bloomberg.com'],
    feedIds: ['bloomberg'],
    bias: 'lean-left',
    biasScore: -1,
    factuality: 'high',
    owner: 'Bloomberg L.P.',
    country: 'US',
  },
  // Right / lean-right
  {
    id: 'wsj',
    name: 'The Wall Street Journal',
    homepage: 'https://www.wsj.com',
    domains: ['wsj.com', 'dj.com'],
    feedIds: ['wsj'],
    bias: 'lean-right',
    biasScore: 1.5,
    factuality: 'mixed',
    owner: 'News Corp (Dow Jones)',
    country: 'US',
  },
  {
    id: 'telegraph',
    name: 'The Telegraph',
    homepage: 'https://www.telegraph.co.uk',
    domains: ['telegraph.co.uk'],
    feedIds: ['telegraph'],
    bias: 'right',
    biasScore: 3,
    factuality: 'mixed',
    owner: 'Telegraph Media Group',
    country: 'UK',
  },
  {
    id: 'globeandmail',
    name: 'The Globe and Mail',
    homepage: 'https://www.theglobeandmail.com',
    domains: ['theglobeandmail.com'],
    feedIds: ['globeandmail'],
    bias: 'lean-right',
    biasScore: 1.5,
    factuality: 'high',
    owner: 'The Woodbridge Company',
    country: 'CA',
  },
  {
    id: 'jpost',
    name: 'The Jerusalem Post',
    homepage: 'https://www.jpost.com',
    domains: ['jpost.com'],
    feedIds: ['jpost'],
    bias: 'lean-right',
    biasScore: 1.5,
    factuality: 'high',
    owner: 'Jpost Inc.',
    country: 'IL',
  },
  {
    id: 'standard_uk',
    name: 'Evening Standard',
    homepage: 'https://www.standard.co.uk',
    domains: ['standard.co.uk'],
    feedIds: ['standard_uk'],
    bias: 'lean-right',
    biasScore: 1.5,
    factuality: 'mixed',
    owner: 'Evgeny Lebedev',
    country: 'UK',
  },
];

/** feedId → sourceId lookup, derived from the seed's `feedIds`. */
export const feedIdToSourceId: Record<string, string> = Object.fromEntries(
  newsSourceSeeds.flatMap((s) => s.feedIds.map((fid) => [fid, s.id] as const)),
);

/** sourceId → seed lookup. */
export const sourceById: Record<string, NewsSourceSeed> = Object.fromEntries(
  newsSourceSeeds.map((s) => [s.id, s] as const),
);
